<?php

namespace EasyCorp\Bundle\EasyAdminBundle\Tests\Functional\Default;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class CustomFormPageControllerTest extends WebTestCase
{
    public function testCustomFormUsesEasyAdminFormThemeInsideAdminContext(): void
    {
        $client = static::createClient();
        $client->request('GET', '/admin/custom-page-with-form');

        $this->assertResponseIsSuccessful();
        // the custom page renders the full admin layout
        $this->assertSelectorExists('body.ea.page-content');
        // the form rows use the markup generated by EasyAdmin's form theme
        $this->assertSelectorExists('.form-group');
        $this->assertSelectorExists('.form-widget input.form-control');
        $this->assertSelectorExists('.form-widget textarea.form-control');
        $this->assertSelectorExists('.form-widget select.form-select');
        $this->assertSelectorTextContains('.form-help', 'Your full name');
    }

    public function testEasyAdminFormThemeWorksWithoutAdminContext(): void
    {
        $client = static::createClient();
        $client->request('GET', '/custom-form-without-admin-context');

        $this->assertResponseIsSuccessful();
        $this->assertSelectorExists('.form-group');
        $this->assertSelectorExists('.form-widget input.form-control');
        $this->assertSelectorExists('.form-widget textarea.form-control');
        $this->assertSelectorExists('.form-widget select.form-select');
        $this->assertSelectorTextContains('.form-help', 'Your full name');
    }
}
